<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TAMBAH (1)</name>
   <tag></tag>
   <elementGuidId>8ce9611c-de21-4b65-92cc-b3412505373e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add_data']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add_data</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c4da224-9a53-4a1e-96f4-b894d936d918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22c51867-4b0e-4bbc-bcb9-e269e37712c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_data</value>
      <webElementGuid>1d262451-cd50-45d3-84a5-4826a5705aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn text-white</value>
      <webElementGuid>c034f536-58f0-4e5a-968f-9eaea6b6d622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TAMBAH</value>
      <webElementGuid>9bf5747d-8f3f-4c3f-b913-7932e743a81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_data&quot;)</value>
      <webElementGuid>0fc41603-8652-41d4-b156-c03c29600af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add_data']</value>
      <webElementGuid>1ee76edc-230e-4d1c-bc5c-1bf134922a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-right']/div/div/div[3]/button</value>
      <webElementGuid>27c8555d-1197-4547-953f-a2c72b48da3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode'])[2]/following::button[1]</value>
      <webElementGuid>50703a14-39f6-4939-9d67-a5452fbbcce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount'])[2]/following::button[1]</value>
      <webElementGuid>c9794033-55e4-476a-b3cc-78957155a302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Session expired'])[1]/preceding::button[1]</value>
      <webElementGuid>0ac0cc69-30dd-4c0f-b95a-da7383845009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go To Login'])[1]/preceding::button[1]</value>
      <webElementGuid>91135293-e1be-4a3c-bd1b-3296c8993738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TAMBAH']/parent::*</value>
      <webElementGuid>fccb5546-c620-4ccb-9a2b-34db00f6026e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>8cd0dfb1-efdc-40b2-afa9-46edc235908e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'add_data' and (text() = 'TAMBAH' or . = 'TAMBAH')]</value>
      <webElementGuid>817e20da-1aaf-436b-a0d9-8194a7e69031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
