<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Periode_periode1 (2)</name>
   <tag></tag>
   <elementGuidId>2871343d-9124-4c9b-8e36-84c2c10f934e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='periode1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#periode1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dda99643-5658-4f8d-909c-16e2f74ecd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1860269e-1b44-431f-badc-c2e8fdbb6157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pull-right</value>
      <webElementGuid>99ad08b5-88f5-4efc-a120-ea5d21d60511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>periode1</value>
      <webElementGuid>da922f6c-6c49-4ff7-b598-5a498d6180e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan periode</value>
      <webElementGuid>c9238bba-fb67-4eee-bcf9-d204ccd1cc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>09f96c57-a272-4540-bb73-4316b00c1d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;periode1&quot;)</value>
      <webElementGuid>b188e9a7-d58d-4705-b5ba-774594b9d0cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='periode1']</value>
      <webElementGuid>e02975cb-2e6d-48ea-9165-75b1452e81b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-right']/div/div/div[2]/form/div/div[6]/div/div/input</value>
      <webElementGuid>5bfd42f6-6d6b-4e5b-93cf-d58a714bff6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>98df633a-107b-45b2-a2da-0b9ca4d96884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'periode1' and @placeholder = 'Masukkan periode']</value>
      <webElementGuid>2f1bc364-bab4-4a64-ba4e-1db45ec3d3d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
