<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Code_usercode1</name>
   <tag></tag>
   <elementGuidId>2c73a8f1-6ec6-49c0-8179-f23b64c80a33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usercode1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#usercode1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b99f26f-cd49-4b74-ac38-42757a888aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bf183d2-7ea3-4f10-a1c4-3ab17e6b37ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pull-right</value>
      <webElementGuid>15e345f2-e832-4755-bebb-6c5407e4ce76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usercode1</value>
      <webElementGuid>47e6af4e-9c5b-400f-abf5-20e3e0b6c7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan User Code</value>
      <webElementGuid>df0c1b38-5f61-451d-aa64-e25833a57a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>c1b8e761-ebec-4702-9de0-9ffecf79922f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usercode1&quot;)</value>
      <webElementGuid>6cea98d9-7595-47b6-b629-78a7be26a65b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usercode1']</value>
      <webElementGuid>5d9e6f37-5041-42c5-8786-179f99f3eff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-right']/div/div/div[2]/form/div/div[2]/div/div/input</value>
      <webElementGuid>a5e98131-5b4d-4cd7-afe2-418d7441349c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>fa3684c6-a145-4e06-abb7-2c864ee8e3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'usercode1' and @placeholder = 'Masukkan User Code']</value>
      <webElementGuid>4ac0a225-4012-4e8a-87bf-40db31daaaa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
