<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ikon detail</name>
   <tag></tag>
   <elementGuidId>41e1d9e9-c9b7-40ff-b945-b224c4b393e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datalist']/tbody/tr[3]/td[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.glyphicon.glyphicon-option-horizontal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93bab983-5d05-4e49-9f31-d9bb29bdc1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev140.ids.id:93/Setorku/upload-detail-1738-OTO_MDN_$%^&amp;*()_090623072342-OTO</value>
      <webElementGuid>5734ffcd-dbad-49c1-b7e2-b3f3ee512230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-option-horizontal</value>
      <webElementGuid>16a41894-62a7-4149-9330-e4dca254243a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datalist&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[9]/a[@class=&quot;glyphicon glyphicon-option-horizontal&quot;]</value>
      <webElementGuid>0fda3b2a-3335-42ab-9818-3feda6c54f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datalist']/tbody/tr[3]/td[9]/a</value>
      <webElementGuid>ff40f57d-473c-4fa4-bd87-fa0067a1a85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev140.ids.id:93/Setorku/upload-detail-1738-OTO_MDN_$%^&amp;*()_090623072342-OTO')]</value>
      <webElementGuid>25d25c40-8e8f-4b27-bda9-3b20ad2d196f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[1]/a</value>
      <webElementGuid>4f738a5b-0bb0-4fac-b4f6-a33ead5f7474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev140.ids.id:93/Setorku/upload-detail-1738-OTO_MDN_$%^&amp;*()_090623072342-OTO']</value>
      <webElementGuid>aafe22b3-99d9-406b-a72c-963a3e3dda0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
